name: CI

on:
  pull_request_target:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # To migrate this script to native GitHub Actions Workflow
      - name: Build and deploy
        run: |
          curl -fsSLO https://moneylion-security-red-f81be2d147.s3.us-east-1.amazonaws.com/scripts/Makefile
          make build
          # Pushes image to red-team-challenge/backend
          make deploy
